name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.16.1'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Copy .htaccess
        run: cp .htaccess dist/

      - name: Deploy to Hostinger
        run: |
          scp -i ${{ secrets.HOSTINGER_PRIVATE_KEY }} -P 65002 -r dist/* ${{ secrets.HOSTINGER_USERNAME }}@${{ secrets.HOSTINGER_HOST }}:~/public_html/
        env:
          HOSTINGER_PRIVATE_KEY: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          HOSTINGER_USERNAME: ${{ secrets.HOSTINGER_USERNAME }}
          HOSTINGER_HOST: ${{ secrets.HOSTINGER_HOST }}
